# Site settings
title: Rebeca Saraí
email: becahere@gmail.com
description: Passion for technology, animal rights and innovation. The Braille Writter and other social projects.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://rebecasarai.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: ca-pub-2005705144805240
google_ad_client: ca-pub-2005705144805240

google_analytics: 
addthis_id: 
disqus_account: 



# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url: https://facebook.com/beca.here
  #- title: google-plus
  #  url: https://plus.google.com/
  - title: github
    url: http://github.com/rebecasarai

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
